//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceExplorer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string ArchiveViewer_Compress {
            get {
                return ((string)(this["ArchiveViewer_Compress"]));
            }
            set {
                this["ArchiveViewer_Compress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ArchiveViewer_OneBlock {
            get {
                return ((bool)(this["ArchiveViewer_OneBlock"]));
            }
            set {
                this["ArchiveViewer_OneBlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ArchiveViewer_OpenSelect {
            get {
                return ((bool)(this["ArchiveViewer_OpenSelect"]));
            }
            set {
                this["ArchiveViewer_OpenSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ArchiveViewer_HexMode {
            get {
                return ((bool)(this["ArchiveViewer_HexMode"]));
            }
            set {
                this["ArchiveViewer_HexMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArchiveViewer_InputSDS {
            get {
                return ((string)(this["ArchiveViewer_InputSDS"]));
            }
            set {
                this["ArchiveViewer_InputSDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PCKGViewer_InputPckg {
            get {
                return ((string)(this["PCKGViewer_InputPckg"]));
            }
            set {
                this["PCKGViewer_InputPckg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PCKGViewer_OutputPckg {
            get {
                return ((string)(this["PCKGViewer_OutputPckg"]));
            }
            set {
                this["PCKGViewer_OutputPckg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TextureViewer_Grid {
            get {
                return ((bool)(this["TextureViewer_Grid"]));
            }
            set {
                this["TextureViewer_Grid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BnkViewer_InputWem {
            get {
                return ((string)(this["BnkViewer_InputWem"]));
            }
            set {
                this["BnkViewer_InputWem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double BnkViewer_Volume {
            get {
                return ((double)(this["BnkViewer_Volume"]));
            }
            set {
                this["BnkViewer_Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BnkViewer_Loop {
            get {
                return ((bool)(this["BnkViewer_Loop"]));
            }
            set {
                this["BnkViewer_Loop"] = value;
            }
        }
    }
}
